### ISSUE TITLE
Why is NodeBuffer marked @deprecated?

### ISSUE THREAD

**Issue by thw0rted** [jsweet-candies/candy-node#1]
I noticed that the [NodeBuffer](https://github.com/jsweet-candies/candy-node/blob/master/src/main/java/def/node/NodeBuffer.java) class is marked `@deprecated` at the top level.  This causes all its inherited methods (like `Buffer#writeUInt8`, etc) to flag with a deprecation warning in an intelligent editor (I'm using VS Code, but I'm confident it would be a problem elsewhere).  Was that intentional?  The methods on `Buffer` certainly aren't deprecated, per [the docs](https://nodejs.org/api/buffer.html).

**Comment by lgrignon** [comment]
cf https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v4/index.d.ts#L558

Candies are generated from TS defs

**Comment by thw0rted** [comment]
This might be two things.  First, I will put in a pull request against DefinitelyTyped -- there is no reference to `NodeBuffer` anywhere on `nodejs.org`, everything refers simply to `Buffer`. As far as I can tell there's no reason for that type to exist at all.  That's a DT issue and I will get it fixed (or figure out why it's supposed to be this way, which is not obvious.)

Second, I believe that in vanilla TS, deprecation isn't inherited the way Java (or maybe just the JSweet transpiler?) handles it:

````
/** @deprecated */ interface DepInt {
    foo: number;
    /** @deprecated */ bar(): boolean;
}

interface NotDep extends DepInt {
    baz: string;
}

let dep: DepInt = {
    foo: 1, bar: () => true
};

let nd: NotDep = {
    foo: 1, bar: () => false, baz: "hey"
}

console.log(dep.foo);
console.log(dep.bar());
console.log(nd.foo);
console.log(nd.bar());
````

The language service marks `DepInt`, `dep.bar`, and `nd.bar` as being deprecated.  It does *not* mark `dep.foo` or `nd.foo` as deprecated.  This means that direct consumers of DT's node typings would see `Buffer.alloc` (or whatever) as *not* being deprecated, but Java code that calls this method would get a deprecation warning.

Should I file this as an issue against the main JSweet project?
